---
- hosts: servers


  tasks:

    - name: "Add the Yarn GPG key"
      shell:
        "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/yarn.gpg"


    - name: "Add the Yarn repository"
      shell:
        "echo 'deb [signed-by=/etc/apt/trusted.gpg.d/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"


    - name: "Update APT cache"
      apt:
        update_cache: yes


    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest          


    - name: "Install CURL"
      apt:
        pkg:
          - curl


    - name: Execute script to add NodeJS to repository
      shell:
        "curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash - "


    - name: Install needed software
      apt: 
        pkg: 
          - git
          - yarn
          - nodejs
#          - npm
          - python3
          - python3-pip


    - name: "Install Docker"
      include_role:
        name: geerlingguy.docker


    - name: "Install Prometheus Node Exporter"
      include_role:
        name: prometheus.prometheus.node_exporter

